---
title: "Sturgeon TidBits Encounter Form QAQC"
author: "Sander Elliott"
format: pdf
editor: visual
---

### Packages

```{r}
library(dplyr)
library(ggplot2)
library(sf)
library(ggspatial)
```

# Load Data and Check Characteristics

```{r}
enc_IC <- read.csv("tagsheet_to_tidbits2025/output/UEF_IC_AST_SNS_SE_RAW.csv", 
                   na.strings = "")
enc_RCNT <- read.csv("tagsheet_to_tidbits2025/output/UEF_RCNT_AST_SNS_SE_RAW.csv", 
                     na.strings = "")
glimpse(enc_IC)
glimpse(enc_RCNT)
```

# Initial Capture QAQC

```{r}
ICvalues <- enc_IC %>%
  summarise(across(
    c(TagType, TagManufacturer, TagModel, TagSerialNumber, EstTagLife,
      Acoustic_ID, Acoustic_Sensor_type, Acoustic_.Sensor_idcode,
      Acoustic_Sensor_value, PIT_ID, Radio_Freq),
    ~ list(unique(.))))

str(ICvalues)
ICvalues$TagSerialNumber
ICvalues$Acoustic_ID

IC_acN <- enc_IC %>% 
  summarise(fish = n(),
            tags = n_distinct(Acoustic_ID, na.rm = TRUE))
IC_acN 

```

## Recapture NT QAQC

```{r}
RCNTvalues <- enc_RCNT %>%
  summarise(across(
    c(TagType, TagManufacturer, TagModel, TagSerialNumber, EstTagLife,
      Acoustic_ID, Acoustic_Sensor_type, Acoustic_.Sensor_idcode,
      Acoustic_Sensor_value, PIT_ID, Radio_Freq),
    ~ list(unique(.))))

str(RCNTvalues)
RCNTvalues$TagSerialNumber
RCNTvalues$Acoustic_ID

RCNT_acN <- enc_RCNT %>% 
  summarise(fish = n(),
            tags = n_distinct(Acoustic_ID, na.rm = TRUE))
RCNT_acN 
```

**Make sure fish and tags between sets add up**

## Size QAQC

```{r}
sumszIC <- enc_IC %>% 
  group_by(Species, System) %>% 
  summarise(n_captures = n(),
            min_FL = min(ForkLength..cm.),
            max_FL = max(ForkLength..cm.),
            range_FL = max(ForkLength..cm.) - min(ForkLength..cm.),
            min_TL = min(TotalLength..cm.),
            max_TL = max(TotalLength..cm.),
            range_TL = max(TotalLength..cm.) - min(TotalLength..cm.))
sumszIC
sumszRCNT <- enc_RCNT %>% 
  group_by(Species, System) %>% 
  summarise(n_captures = n(),
            min_FL = min(ForkLength..cm.),
            max_FL = max(ForkLength..cm.),
            range_FL = max(ForkLength..cm.) - min(ForkLength..cm.),
            min_TL = min(TotalLength..cm.),
            max_TL = max(TotalLength..cm.),
            range_TL = max(TotalLength..cm.) - min(TotalLength..cm.))
sumszRCNT
```

### Fix Size

Check tag sheet on AST with FL = 1

```{r}
wrong_FL <- enc_IC %>% 
  filter(ForkLength..cm.< 2)
wrong_FL
## supposed to be 109
enc_IC1 <- enc_IC %>% 
  mutate(ForkLength..cm. = case_when(ForkLength..cm. == 1 ~ 109,
                                     TRUE ~ ForkLength..cm.))

sumszIC1 <- enc_IC1 %>% 
  group_by(Species, System) %>% 
  summarise(n_captures = n(),
            min_FL = min(ForkLength..cm.),
            max_FL = max(ForkLength..cm.),
            range_FL = max(ForkLength..cm.) - min(ForkLength..cm.),
            min_TL = min(TotalLength..cm.),
            max_TL = max(TotalLength..cm.),
            range_TL = max(TotalLength..cm.) - min(TotalLength..cm.))
sumszIC1


```

## Interobital to Mouth

check ratios of IO to Mouth **AST \< 0.55; SNS \> 0.55**

```{r}

ICioRatio <- enc_IC1 %>%
  mutate(ratio = `STRG_InsideMouth.mm.` / `STRG_Interorbital.mm.`) %>%
  filter(!is.na(ratio), is.finite(ratio)) %>% 
  group_by(Species) %>% 
  summarise(min = min(ratio),
            max = max(ratio))

ICioRatio

RCNTioRatio <- enc_IC1 %>%
  mutate(ratio = `STRG_InsideMouth.mm.` / `STRG_Interorbital.mm.`) %>%
  filter(!is.na(ratio), is.finite(ratio)) %>% 
  group_by(Species) %>% 
  summarise(min = min(ratio),
            max = max(ratio))

RCNTioRatio

```

# Map Locations

```{r}

## IC

ICloc_sf <- enc_IC1 %>%
  st_as_sf(coords = c("Encounter_Easting", "Encounter_Northing"), crs = 26919) %>%
  st_transform(crs = 4326) 

ICloc_df <- ICloc_sf %>%
  mutate(Longitude = st_coordinates(.)[,1], Latitude = st_coordinates(.)[,2]) %>%
  as.data.frame()

ggplot(data = ICloc_df) +
  geom_point(aes(x = Longitude, 
                 y = Latitude, 
                 color = Release_Location), 
             size = 2, alpha = 0.7) +
  theme_minimal() 


ggplot(data = ICloc_df) +
  annotation_map_tile(type = "cartolight", zoom = 12) +  
  geom_point(aes(x = Longitude, y = Latitude, color = Release_Location),
             size = 2, alpha = 0.7) +
  coord_sf(crs = 4326, 
           xlim = c(min(ICloc_df$Longitude) - 0.15, 
                    max(ICloc_df$Longitude) + 0.15),
           ylim = c(min(ICloc_df$Latitude) - 0.05,  
                    max(ICloc_df$Latitude) + 0.05),
           expand = FALSE)  +
  labs(title = "IC")+
  theme_minimal()

## RCNT

RCNTloc_sf <- enc_RCNT %>%
  st_as_sf(coords = c("Encounter_Easting", "Encounter_Northing"), crs = 26919) %>%
  st_transform(crs = 4326)  

RCNTloc_df <- RCNTloc_sf %>%
  mutate(Longitude = st_coordinates(.)[,1], Latitude = st_coordinates(.)[,2]) %>%
  as.data.frame()


ggplot(data = RCNTloc_df) +
  geom_point(aes(x = Longitude, 
                 y = Latitude, 
                 color = Release_Location), 
             size = 2, alpha = 0.7) +
  theme_minimal() 


ggplot(data = RCNTloc_df) +
  annotation_map_tile(type = "cartolight", zoom = 12) +  
  geom_point(aes(x = Longitude, y = Latitude, color = Release_Location),
             size = 2, alpha = 0.7) +
  coord_sf(crs = 4326, 
           xlim = c(min(RCNTloc_df$Longitude) - 0.15, 
                    max(RCNTloc_df$Longitude) + 0.15),
           ylim = c(min(RCNTloc_df$Latitude) - 0.05,  
                    max(RCNTloc_df$Latitude) + 0.05),
           expand = FALSE)  +
  labs(title = "RCNT")+
  theme_minimal()
```

## Output csv

```{r}
write.csv(enc_IC1, "2025/output/UEF_IC_AST_SNS_SE.csv", na = "", row.names = FALSE)
write.csv(enc_RCNT, "2025/output/UEF_RCNT_AST_SNS_SE.csv", na = "", row.names = FALSE)
```
